services:
  db1:
    image: postgres:15
    container_name: relatos_db_catalogue
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_catalogue_data:/var/lib/postgresql/data
      - ./database/catalogue/01_catalogue_ddl.sql:/docker-entrypoint-initdb.d/01_catalogue_ddl.sql
      - ./database/catalogue/02_catalogue_dml.sql:/docker-entrypoint-initdb.d/02_catalogue_dml.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d postgres"]
      interval: 10s
      timeout: 5s
      retries: 10
    networks:
      - relatos-net

  db2:
    image: postgres:15
    container_name: relatos_db_orders
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: postgres
    ports:
      - "5433:5432"
    volumes:
      - postgres_orders_data:/var/lib/postgresql/data
      - ./database/orders/01_orders_ddl.sql:/docker-entrypoint-initdb.d/01_orders_ddl.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d postgres"]
      interval: 10s
      timeout: 5s
      retries: 10
    networks:
      - relatos-net

  db3:
    image: postgres:15
    container_name: user_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: users_db
    ports:
      - "5434:5432"
    volumes:
      - postgres_user_data:/var/lib/postgresql/data
      - ./database/users/01_user_ddl.sql:/docker-entrypoint-initdb.d/01_user_ddl.sql
      - ./database/users/02_user_dml.sql:/docker-entrypoint-initdb.d/02_user_dml.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d users_db"]
      interval: 10s
      timeout: 5s
      retries: 10
    networks:
      - relatos-net

  eureka:
    build:
      dockerfile: Dockerfile
      context: ./back-end-eureka
    container_name: relatos_eureka
    environment:
      PORT: 8761
      HOSTNAME: eureka
    ports:
      - "8761:8761"
    networks:
      - relatos-net

  catalogue1:
    build:
      dockerfile: Dockerfile
      context: ./back-end-books-catalogue
    container_name: relatos_catalogue_1
    environment:
      PORT: 8080
      DB_URL: jdbc:postgresql://db1:5432/catalogue_db
      DB_DRIVER: org.postgresql.Driver
      DB_USER: postgres
      DB_PASSWORD: password
      EUREKA_URL: http://eureka:8761/eureka/
      ELASTICSEARCH_HOST: adaptable-magnolia-1q4vm9y0.us-east-1.bonsaisearch.net
      ELASTICSEARCH_USER: 91bb0499c1
      ELASTICSEARCH_PWD: 19b7e18c3c3cd1320b60
    ports:
      - "8081:8080"
    depends_on:
      db1:
        condition: service_healthy
      eureka:
        condition: service_started
    networks:
      - relatos-net

  catalogue2:
    build:
      dockerfile: Dockerfile
      context: ./back-end-books-catalogue
    container_name: relatos_catalogue_2
    environment:
      PORT: 8080
      DB_URL: jdbc:postgresql://db1:5432/catalogue_db
      DB_DRIVER: org.postgresql.Driver
      DB_USER: postgres
      DB_PASSWORD: password
      EUREKA_URL: http://eureka:8761/eureka/
      ELASTICSEARCH_HOST: adaptable-magnolia-1q4vm9y0.us-east-1.bonsaisearch.net
      ELASTICSEARCH_USER: 91bb0499c1
      ELASTICSEARCH_PWD: 19b7e18c3c3cd1320b60
    ports:
      - "8082:8080"
    depends_on:
      db1:
        condition: service_healthy
      eureka:
        condition: service_started
    networks:
      - relatos-net

  orders1:
    build:
      dockerfile: Dockerfile
      context: ./back-end-books-orders
    container_name: relatos_orders_1
    environment:
      PORT: 8080
      DB_URL: jdbc:postgresql://db2:5432/books_orders
      DB_DRIVER: org.postgresql.Driver
      DB_USER: postgres
      DB_PASSWORD: password
      EUREKA_URL: http://eureka:8761/eureka/
      BOOKS_CATALOGUE_URL: http://catalogue-service/api/v1
    depends_on:
      db2:
        condition: service_healthy
      eureka:
        condition: service_started
      catalogue1:
        condition: service_started
      catalogue2:
        condition: service_started
    networks:
      - relatos-net

  orders2:
    build:
      dockerfile: Dockerfile
      context: ./back-end-books-orders
    container_name: relatos_orders_2
    environment:
      PORT: 8080
      DB_URL: jdbc:postgresql://db2:5432/books_orders
      DB_DRIVER: org.postgresql.Driver
      DB_USER: postgres
      DB_PASSWORD: password
      EUREKA_URL: http://eureka:8761/eureka/
      BOOKS_CATALOGUE_URL: http://catalogue-service/api/v1
    depends_on:
      db2:
        condition: service_healthy
      eureka:
        condition: service_started
      catalogue1:
        condition: service_started
      catalogue2:
        condition: service_started
    networks:
      - relatos-net

  orders3:
    build:
      dockerfile: Dockerfile
      context: ./back-end-books-orders
    container_name: relatos_orders_3
    environment:
      PORT: 8080
      DB_URL: jdbc:postgresql://db2:5432/books_orders
      DB_DRIVER: org.postgresql.Driver
      DB_USER: postgres
      DB_PASSWORD: password
      EUREKA_URL: http://eureka:8761/eureka/
      BOOKS_CATALOGUE_URL: http://catalogue-service/api/v1
    depends_on:
      db2:
        condition: service_healthy
      eureka:
        condition: service_started
      catalogue1:
        condition: service_started
      catalogue2:
        condition: service_started
    networks:
      - relatos-net

  users:
    build:
      dockerfile: Dockerfile
      context: ./back-end-users
    container_name: users-service
    environment:
      PORT: 8080
      DB_URL: jdbc:postgresql://db3:5432/users_db
      DB_DRIVER: org.postgresql.Driver
      DB_USER: postgres
      DB_PASSWORD: password
      EUREKA_URL: http://eureka:8761/eureka/
      REDIS_HOST: redis
      REDIS_PORT: 6379
    depends_on:
      db3:
        condition: service_healthy
      eureka:
        condition: service_started
      redis:
        condition: service_started
    networks:
      - relatos-net

  comms:
    build:
      dockerfile: Dockerfile
      context: ./back-end-comms-service
    container_name: comms-service
    environment:
      PORT: 8080
      EUREKA_URL: http://eureka:8761/eureka/
      GEMINI_API_KEY: ${GEMINI_API_KEY}
    ports:
      - "8085:8080"
    depends_on:
      eureka:
        condition: service_started
    networks:
      - relatos-net

  gateway:
    build:
      dockerfile: Dockerfile
      context: ./back-end-gateway
    container_name: relatos_gateway
    ports:
      - "8762:8762"
    environment:
      EUREKA_URL: http://eureka:8761/eureka/
      ALLOWED_ORIGINS: "*"
      USERS_SERVICE_URL: http://users-service:8080
    depends_on:
      eureka:
        condition: service_started
      catalogue1:
        condition: service_started
      catalogue2:
        condition: service_started
      orders1:
        condition: service_started
      orders2:
        condition: service_started
      orders3:
        condition: service_started
      users:
        condition: service_started
      comms:
        condition: service_started
    networks:
      - relatos-net

  redis:
    image: redis:7
    container_name: relatos_redis
    ports:
      - "6379:6379"
    networks:
      - relatos-net

volumes:
  postgres_catalogue_data:
  postgres_orders_data:
  postgres_user_data:

networks:
  relatos-net:
    driver: bridge