### test books gateway
GET http://localhost:8762/catalogue-service/api/v1/books

### create order from gateway
POST http://localhost:8762/orders-service/api/v1/orders
Content-Type: application/json

{
  "items": [
    {
      "id": "00000000-0000-0000-0000-000000000032",
      "quantity": 1
    }
  ]
}
