
server:
  port: 8080

spring:
  application:
    name: books-orders

  ## Database Configuration
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/books_orders}
    driver-class-name: ${DB_DRIVER:org.postgresql.Driver}
    username: ${DB_USER:root}
    password: ${DB_PASSWORD:password}
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        format_sql: true

## Logging Configuration
logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    org.springframework.data.jpa: DEBUG

## Eureka Client Configuration
eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URL:http://localhost:8761/eureka}
  instance:
    preferIpAddress: true
    hostname: unir-supplies-catalogue

## Microservices Configuration
ordersCatalogue:
  url: ${SUPPLIES_CATALOGUE_URL:http://orders-catalogue/api/v1}