#server:
#port: 8080

spring:
  application:
    name: orders-service

  ## Database Configuration
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/books_orders}
    driver-class-name: ${DB_DRIVER:org.postgresql.Driver}
    username: ${DB_USER:root}
    password: ${DB_PASSWORD:password}

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true

## Logging Configuration
logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    org.springframework.data.jpa: DEBUG

## Eureka Client Configuration
eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URL:http://localhost:8761/eureka}
  instance:
    preferIpAddress: true

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always
  info:
    env:
      enabled: true

## Microservices Configuration
booksCatalogue:
  url: ${BOOKS_CATALOGUE_URL:http://gateway:5678/catalogue/api/v1}

info:
  app:
    name: orders-service
    description: Microservicio de órdenes para Relatos de Papel
    version: 1.0.0
