#server:
#port: 8080

spring:
  application:
    name: orders-service

  ## Database Configuration
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/books_orders}
    driver-class-name: ${DB_DRIVER:org.postgresql.Driver}
    username: ${DB_USER:root}
    password: ${DB_PASSWORD:password}

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URL:http://localhost:8761/eureka/}
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true

management:
  endpoints:
    web:
      exposure:
        include: health,info

booksCatalogue:
  url: ${BOOKS_CATALOGUE_URL:http://localhosst:8081/api/v1}