server:
  port: ${PORT:8762}

## Classic Eureka configuration
eureka:
  instance:
    prefer-ip-address: ${EUREKA_PREFER_IP:true}
    hostname: ${EUREKA_HOSTNAME:localhost}
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: ${EUREKA_URL:http://localhost:8761/eureka}

## Enable service discovery (with Eureka)
spring:
  application:
    name: gateway
  cloud:
    gateway:
      server:
        webflux:
          # 1. Registro de rutas reactivas
          routes:
            - id: comms-service-websocket
              uri: lb://ws://COMMS-SERVICE
              predicates:
                - name: Path
                  args:
                    patterns: /comms-service/ws/**
              filters:
                - name: RewritePath
                  args:
                    regexp: /comms-service/?(?<remaining>.*)
                    replacement: /${remaining}
          discovery:
            locator:
              enabled: true
              lower-case-service-id: true
          default-filters:
            - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
          globalcors:
            cors-configurations:
              '[/**]':
                allowedOrigins: ${ALLOWED_ORIGINS:*}
                allowedHeaders: "*"
                allowedMethods:
                  - POST
                  - GET # Handshake del WebSocket

management:
  endpoint:
    gateway:
      access: ${ROUTE_TABLES_ENABLED:read_only}
  endpoints:
    web:
      exposure:
        include:
          - '*'

services:
  users:
    url: ${USERS_SERVICE_URL:http://users-service:8080}