server:
  port: ${PORT:8763}

<<<<<<< HEAD
## Classic Eureka configuration
eureka:
  instance:
    preferIpAddress: false
    hostname: ${HOSTNAME:localhost}

  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: ${EUREKA_URL:http://localhost:8762/eureka}


## Enable service discovery (with Eureka)
## lower-case-service-id is mandatory, otherwise is retrieved in upper case from Eureka
=======
>>>>>>> origin/main
spring:
  application:
    name: gateway

  cloud:
    gateway:
      server:
        webflux:
          discovery:
            locator:
              enabled: true
              lower-case-service-id: true

          default-filters:
            - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin

          globalcors:
            cors-configurations:
              '[/**]':
                allowedOrigins: ${ALLOWED_ORIGINS:*}
                allowedHeaders: "*"
                allowedMethods:
                  - POST
<<<<<<< HEAD
=======
                  - PUT
                  - DELETE
                  - PATCH
                  - OPTIONS

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URL:http://localhost:8761/eureka/}
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true
>>>>>>> origin/main

management:
  endpoints:
    web:
      exposure:
        include:
          - '*'