server:
  port: ${PORT:8762}

## Classic Eureka configuration
eureka:
  instance:
    prefer-ip-address: ${EUREKA_PREFER_IP:true}
    hostname: ${EUREKA_HOSTNAME:localhost}
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: ${EUREKA_URL:http://localhost:8761/eureka}

spring:
  application:
    name: gateway

  cloud:
    gateway:
      httpclient:
        pool:
          max-idle-time: 30s

      server:
        webflux:
          routes:
            - id: comms-service-websocket
              uri: lb://ws://comms-service
              predicates:
                - name: Path
                  args:
                    patterns: /comms-service/ws/**
                - name: Header
                  args:
                    header: Upgrade
                    regexp: (?i)websocket   # Insensible a mayúsculas/minúsculas
              filters:
                - name: StripPrefix
                  args:
                    parts: 1
                - name: PreserveHostHeader  # Mantiene el host original en la red de Railway

            # --- RUTA 2: HTTP DE SOCKJS (Maneja /info, /xhr, etc.) ---
            - id: comms-service-sockjs-http
              uri: lb://comms-service
              predicates:
                - name: Path
                  args:
                    patterns: /comms-service/ws/**
              filters:
                - name: StripPrefix
                  args:
                    parts: 1

          # 2. DISCOVERY LOCATOR
          discovery:
            locator:
              enabled: true
              lower-case-service-id: true

          # 3. FILTROS POR DEFECTO
          default-filters:
            - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin

          # 4. CORS GLOBAL
          globalcors:
            cors-configurations:
              '[/**]':
                allowedOrigins: ${ALLOWED_ORIGINS:*}
                allowedHeaders: "*"
                allowedMethods:
                  - GET
                  - POST

management:
  endpoint:
    gateway:
      access: ${ROUTE_TABLES_ENABLED:read_only}
  endpoints:
    web:
      exposure:
        include:
          - '*'

services:
  users:
    url: ${USERS_SERVICE_URL:http://users-service:8080}