server:
  port: 8081

spring:
  application:
    name: catalogue-service

  datasource:
    url: jdbc:postgresql://localhost:5432/catalogue_db
    username: postgres
    password: Adrian30@

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/