server:
  port: ${PORT:8080}

spring:
  application:
    name: catalogue-service

  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/catalogue_db}
    username: ${DB_USER:root}
    password: ${DB_PASSWORD:admin}
    driver-class-name: ${DB_DRIVER:org.postgresql.Driver}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URL:http://localhost:8761/eureka/}
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: ${EUREKA_PREFER_IP:true}
    hostname: ${EUREKA_HOSTNAME:localhost}

opensearch:
  host: ${ELASTICSEARCH_HOST}
  credentials:
    user: ${ELASTICSEARCH_USER}
    password: ${ELASTICSEARCH_PWD}

management:
  endpoints:
    web:
      exposure:
        include: health,info