server:
  port: ${PORT:8082}

spring:
  application:
    name: comms-service

    ##Rabbitmq configuracion
  RabbitMQ:
    host: ${RABBITMQ_HOST:localhost}
    port: ${RABBITMQ_PORT:5672}
    username: ${RABBITMQ_USER:admin}
    password: ${RABBITMQ_PASSWORD:admin}
    virtual-host: ${RABBITMQ_VHOST:/}

    ##Configuracion  mail


  mail:
    host: ${MAIL_HOST}
    port: ${MAIL_PORT}
    username: ${MAIL_USER}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        transport:
          protocol: smtp
        smtp:
          auth: ${MAIL_AUTH:false}
          starttls:
            enable: ${MAIL_STARTTLS:true}
            required: ${MAIL_STARTTLS_REQUIRED:true}
          ssl:
            trust: ${TRUST_MAIL}

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URL:http://localhost:8761/eureka/}
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: ${EUREKA_PREFER_IP:true}
    hostname: ${EUREKA_HOSTNAME:localhost}

management:
  endpoints:
    web:
      exposure:
        include: health,info

## RabbitMQ Event Configuration
rabbitmq:
  queue:
    mails:
      order-created: mail.orden.creada
  exchange:
    orders: pedido.creado
  routing:
    key:
      order:
        created: order.created

gemini:
  api-key: ${GEMINI_API_KEY}

# Configuración de notificaciones por correo
email:
  notification:
    to: ${NOTIFICATION_EMAIL:unir.supplies@gmail.com} # Cambia esto por el correo del destinatario
    from: ${FROM_EMAIL:UNIR Supplies - Tu tienda de suministros <unir.supplies@gmail.com>}
