server:
  port: ${PORT:8761}

spring:
  application:
    name: eureka-server

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
  instance:
    hostname: ${EUREKA_HOST:localhost}
  server:
    renewal-percent-threshold: 0.90

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always
  info:
    env:
      enabled: true

info:
  app:
    name: eureka-service
    description: Servidor Eureka para descubrimiento de microservicios de Relatos de Papel
    version: 1.0.0